# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_tools_pb2 as game__tools__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameToolsServiceStub(object):
    """Game Tools service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeckQuery = channel.unary_unary(
                '/game_tools.GameToolsService/DeckQuery',
                request_serializer=game__tools__pb2.DeckQueryRequest.SerializeToString,
                response_deserializer=game__tools__pb2.DeckQueryResponse.FromString,
                _registered_method=True)
        self.RevealTop = channel.unary_unary(
                '/game_tools.GameToolsService/RevealTop',
                request_serializer=game__tools__pb2.RevealTopRequest.SerializeToString,
                response_deserializer=game__tools__pb2.RevealTopResponse.FromString,
                _registered_method=True)
        self.MoveCard = channel.unary_unary(
                '/game_tools.GameToolsService/MoveCard',
                request_serializer=game__tools__pb2.MoveCardRequest.SerializeToString,
                response_deserializer=game__tools__pb2.MoveCardResponse.FromString,
                _registered_method=True)
        self.Shuffle = channel.unary_unary(
                '/game_tools.GameToolsService/Shuffle',
                request_serializer=game__tools__pb2.ShuffleRequest.SerializeToString,
                response_deserializer=game__tools__pb2.ShuffleResponse.FromString,
                _registered_method=True)
        self.Draw = channel.unary_unary(
                '/game_tools.GameToolsService/Draw',
                request_serializer=game__tools__pb2.DrawRequest.SerializeToString,
                response_deserializer=game__tools__pb2.DrawResponse.FromString,
                _registered_method=True)
        self.Discard = channel.unary_unary(
                '/game_tools.GameToolsService/Discard',
                request_serializer=game__tools__pb2.DiscardRequest.SerializeToString,
                response_deserializer=game__tools__pb2.DiscardResponse.FromString,
                _registered_method=True)
        self.TakePrize = channel.unary_unary(
                '/game_tools.GameToolsService/TakePrize',
                request_serializer=game__tools__pb2.TakePrizeRequest.SerializeToString,
                response_deserializer=game__tools__pb2.TakePrizeResponse.FromString,
                _registered_method=True)
        self.RandomDiscard = channel.unary_unary(
                '/game_tools.GameToolsService/RandomDiscard',
                request_serializer=game__tools__pb2.RandomDiscardRequest.SerializeToString,
                response_deserializer=game__tools__pb2.RandomDiscardResponse.FromString,
                _registered_method=True)
        self.QueryDiscard = channel.unary_unary(
                '/game_tools.GameToolsService/QueryDiscard',
                request_serializer=game__tools__pb2.QueryDiscardRequest.SerializeToString,
                response_deserializer=game__tools__pb2.QueryDiscardResponse.FromString,
                _registered_method=True)
        self.QueryPrizeCount = channel.unary_unary(
                '/game_tools.GameToolsService/QueryPrizeCount',
                request_serializer=game__tools__pb2.QueryPrizeCountRequest.SerializeToString,
                response_deserializer=game__tools__pb2.QueryPrizeCountResponse.FromString,
                _registered_method=True)
        self.SwapActiveWithBench = channel.unary_unary(
                '/game_tools.GameToolsService/SwapActiveWithBench',
                request_serializer=game__tools__pb2.SwapActiveWithBenchRequest.SerializeToString,
                response_deserializer=game__tools__pb2.SwapActiveWithBenchResponse.FromString,
                _registered_method=True)
        self.ShuffleHandIntoDeck = channel.unary_unary(
                '/game_tools.GameToolsService/ShuffleHandIntoDeck',
                request_serializer=game__tools__pb2.ShuffleHandIntoDeckRequest.SerializeToString,
                response_deserializer=game__tools__pb2.ShuffleHandIntoDeckResponse.FromString,
                _registered_method=True)
        self.EvolvePokemon = channel.unary_unary(
                '/game_tools.GameToolsService/EvolvePokemon',
                request_serializer=game__tools__pb2.EvolvePokemonRequest.SerializeToString,
                response_deserializer=game__tools__pb2.EvolvePokemonResponse.FromString,
                _registered_method=True)
        self.UpdateDamage = channel.unary_unary(
                '/game_tools.GameToolsService/UpdateDamage',
                request_serializer=game__tools__pb2.UpdateDamageRequest.SerializeToString,
                response_deserializer=game__tools__pb2.UpdateDamageResponse.FromString,
                _registered_method=True)
        self.CheckKO = channel.unary_unary(
                '/game_tools.GameToolsService/CheckKO',
                request_serializer=game__tools__pb2.CheckKORequest.SerializeToString,
                response_deserializer=game__tools__pb2.CheckKOResponse.FromString,
                _registered_method=True)
        self.AttachEnergy = channel.unary_unary(
                '/game_tools.GameToolsService/AttachEnergy',
                request_serializer=game__tools__pb2.AttachEnergyRequest.SerializeToString,
                response_deserializer=game__tools__pb2.AttachEnergyResponse.FromString,
                _registered_method=True)
        self.TrackUsage = channel.unary_unary(
                '/game_tools.GameToolsService/TrackUsage',
                request_serializer=game__tools__pb2.TrackUsageRequest.SerializeToString,
                response_deserializer=game__tools__pb2.TrackUsageResponse.FromString,
                _registered_method=True)
        self.GetUsageCount = channel.unary_unary(
                '/game_tools.GameToolsService/GetUsageCount',
                request_serializer=game__tools__pb2.GetUsageCountRequest.SerializeToString,
                response_deserializer=game__tools__pb2.GetUsageCountResponse.FromString,
                _registered_method=True)
        self.SendToLostZone = channel.unary_unary(
                '/game_tools.GameToolsService/SendToLostZone',
                request_serializer=game__tools__pb2.SendToLostZoneRequest.SerializeToString,
                response_deserializer=game__tools__pb2.SendToLostZoneResponse.FromString,
                _registered_method=True)
        self.RevealPrize = channel.unary_unary(
                '/game_tools.GameToolsService/RevealPrize',
                request_serializer=game__tools__pb2.RevealPrizeRequest.SerializeToString,
                response_deserializer=game__tools__pb2.RevealPrizeResponse.FromString,
                _registered_method=True)
        self.ModifyPrizeDelta = channel.unary_unary(
                '/game_tools.GameToolsService/ModifyPrizeDelta',
                request_serializer=game__tools__pb2.ModifyPrizeDeltaRequest.SerializeToString,
                response_deserializer=game__tools__pb2.ModifyPrizeDeltaResponse.FromString,
                _registered_method=True)
        self.SetSpecialCondition = channel.unary_unary(
                '/game_tools.GameToolsService/SetSpecialCondition',
                request_serializer=game__tools__pb2.SetSpecialConditionRequest.SerializeToString,
                response_deserializer=game__tools__pb2.SetSpecialConditionResponse.FromString,
                _registered_method=True)


class GameToolsServiceServicer(object):
    """Game Tools service definition
    """

    def DeckQuery(self, request, context):
        """Deck and card queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevealTop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveCard(self, request, context):
        """Card movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shuffle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Draw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakePrize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RandomDiscard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDiscard(self, request, context):
        """Zone queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPrizeCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapActiveWithBench(self, request, context):
        """Enhanced operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShuffleHandIntoDeck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolvePokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDamage(self, request, context):
        """Damage and combat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckKO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachEnergy(self, request, context):
        """Energy attachment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackUsage(self, request, context):
        """Usage tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendToLostZone(self, request, context):
        """Lost Zone operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevealPrize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyPrizeDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpecialCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameToolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeckQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.DeckQuery,
                    request_deserializer=game__tools__pb2.DeckQueryRequest.FromString,
                    response_serializer=game__tools__pb2.DeckQueryResponse.SerializeToString,
            ),
            'RevealTop': grpc.unary_unary_rpc_method_handler(
                    servicer.RevealTop,
                    request_deserializer=game__tools__pb2.RevealTopRequest.FromString,
                    response_serializer=game__tools__pb2.RevealTopResponse.SerializeToString,
            ),
            'MoveCard': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveCard,
                    request_deserializer=game__tools__pb2.MoveCardRequest.FromString,
                    response_serializer=game__tools__pb2.MoveCardResponse.SerializeToString,
            ),
            'Shuffle': grpc.unary_unary_rpc_method_handler(
                    servicer.Shuffle,
                    request_deserializer=game__tools__pb2.ShuffleRequest.FromString,
                    response_serializer=game__tools__pb2.ShuffleResponse.SerializeToString,
            ),
            'Draw': grpc.unary_unary_rpc_method_handler(
                    servicer.Draw,
                    request_deserializer=game__tools__pb2.DrawRequest.FromString,
                    response_serializer=game__tools__pb2.DrawResponse.SerializeToString,
            ),
            'Discard': grpc.unary_unary_rpc_method_handler(
                    servicer.Discard,
                    request_deserializer=game__tools__pb2.DiscardRequest.FromString,
                    response_serializer=game__tools__pb2.DiscardResponse.SerializeToString,
            ),
            'TakePrize': grpc.unary_unary_rpc_method_handler(
                    servicer.TakePrize,
                    request_deserializer=game__tools__pb2.TakePrizeRequest.FromString,
                    response_serializer=game__tools__pb2.TakePrizeResponse.SerializeToString,
            ),
            'RandomDiscard': grpc.unary_unary_rpc_method_handler(
                    servicer.RandomDiscard,
                    request_deserializer=game__tools__pb2.RandomDiscardRequest.FromString,
                    response_serializer=game__tools__pb2.RandomDiscardResponse.SerializeToString,
            ),
            'QueryDiscard': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDiscard,
                    request_deserializer=game__tools__pb2.QueryDiscardRequest.FromString,
                    response_serializer=game__tools__pb2.QueryDiscardResponse.SerializeToString,
            ),
            'QueryPrizeCount': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPrizeCount,
                    request_deserializer=game__tools__pb2.QueryPrizeCountRequest.FromString,
                    response_serializer=game__tools__pb2.QueryPrizeCountResponse.SerializeToString,
            ),
            'SwapActiveWithBench': grpc.unary_unary_rpc_method_handler(
                    servicer.SwapActiveWithBench,
                    request_deserializer=game__tools__pb2.SwapActiveWithBenchRequest.FromString,
                    response_serializer=game__tools__pb2.SwapActiveWithBenchResponse.SerializeToString,
            ),
            'ShuffleHandIntoDeck': grpc.unary_unary_rpc_method_handler(
                    servicer.ShuffleHandIntoDeck,
                    request_deserializer=game__tools__pb2.ShuffleHandIntoDeckRequest.FromString,
                    response_serializer=game__tools__pb2.ShuffleHandIntoDeckResponse.SerializeToString,
            ),
            'EvolvePokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolvePokemon,
                    request_deserializer=game__tools__pb2.EvolvePokemonRequest.FromString,
                    response_serializer=game__tools__pb2.EvolvePokemonResponse.SerializeToString,
            ),
            'UpdateDamage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDamage,
                    request_deserializer=game__tools__pb2.UpdateDamageRequest.FromString,
                    response_serializer=game__tools__pb2.UpdateDamageResponse.SerializeToString,
            ),
            'CheckKO': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckKO,
                    request_deserializer=game__tools__pb2.CheckKORequest.FromString,
                    response_serializer=game__tools__pb2.CheckKOResponse.SerializeToString,
            ),
            'AttachEnergy': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachEnergy,
                    request_deserializer=game__tools__pb2.AttachEnergyRequest.FromString,
                    response_serializer=game__tools__pb2.AttachEnergyResponse.SerializeToString,
            ),
            'TrackUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackUsage,
                    request_deserializer=game__tools__pb2.TrackUsageRequest.FromString,
                    response_serializer=game__tools__pb2.TrackUsageResponse.SerializeToString,
            ),
            'GetUsageCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageCount,
                    request_deserializer=game__tools__pb2.GetUsageCountRequest.FromString,
                    response_serializer=game__tools__pb2.GetUsageCountResponse.SerializeToString,
            ),
            'SendToLostZone': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToLostZone,
                    request_deserializer=game__tools__pb2.SendToLostZoneRequest.FromString,
                    response_serializer=game__tools__pb2.SendToLostZoneResponse.SerializeToString,
            ),
            'RevealPrize': grpc.unary_unary_rpc_method_handler(
                    servicer.RevealPrize,
                    request_deserializer=game__tools__pb2.RevealPrizeRequest.FromString,
                    response_serializer=game__tools__pb2.RevealPrizeResponse.SerializeToString,
            ),
            'ModifyPrizeDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyPrizeDelta,
                    request_deserializer=game__tools__pb2.ModifyPrizeDeltaRequest.FromString,
                    response_serializer=game__tools__pb2.ModifyPrizeDeltaResponse.SerializeToString,
            ),
            'SetSpecialCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpecialCondition,
                    request_deserializer=game__tools__pb2.SetSpecialConditionRequest.FromString,
                    response_serializer=game__tools__pb2.SetSpecialConditionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_tools.GameToolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game_tools.GameToolsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameToolsService(object):
    """Game Tools service definition
    """

    @staticmethod
    def DeckQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/DeckQuery',
            game__tools__pb2.DeckQueryRequest.SerializeToString,
            game__tools__pb2.DeckQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevealTop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/RevealTop',
            game__tools__pb2.RevealTopRequest.SerializeToString,
            game__tools__pb2.RevealTopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/MoveCard',
            game__tools__pb2.MoveCardRequest.SerializeToString,
            game__tools__pb2.MoveCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shuffle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/Shuffle',
            game__tools__pb2.ShuffleRequest.SerializeToString,
            game__tools__pb2.ShuffleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Draw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/Draw',
            game__tools__pb2.DrawRequest.SerializeToString,
            game__tools__pb2.DrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/Discard',
            game__tools__pb2.DiscardRequest.SerializeToString,
            game__tools__pb2.DiscardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakePrize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/TakePrize',
            game__tools__pb2.TakePrizeRequest.SerializeToString,
            game__tools__pb2.TakePrizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RandomDiscard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/RandomDiscard',
            game__tools__pb2.RandomDiscardRequest.SerializeToString,
            game__tools__pb2.RandomDiscardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDiscard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/QueryDiscard',
            game__tools__pb2.QueryDiscardRequest.SerializeToString,
            game__tools__pb2.QueryDiscardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPrizeCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/QueryPrizeCount',
            game__tools__pb2.QueryPrizeCountRequest.SerializeToString,
            game__tools__pb2.QueryPrizeCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapActiveWithBench(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/SwapActiveWithBench',
            game__tools__pb2.SwapActiveWithBenchRequest.SerializeToString,
            game__tools__pb2.SwapActiveWithBenchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShuffleHandIntoDeck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/ShuffleHandIntoDeck',
            game__tools__pb2.ShuffleHandIntoDeckRequest.SerializeToString,
            game__tools__pb2.ShuffleHandIntoDeckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolvePokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/EvolvePokemon',
            game__tools__pb2.EvolvePokemonRequest.SerializeToString,
            game__tools__pb2.EvolvePokemonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDamage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/UpdateDamage',
            game__tools__pb2.UpdateDamageRequest.SerializeToString,
            game__tools__pb2.UpdateDamageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckKO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/CheckKO',
            game__tools__pb2.CheckKORequest.SerializeToString,
            game__tools__pb2.CheckKOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachEnergy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/AttachEnergy',
            game__tools__pb2.AttachEnergyRequest.SerializeToString,
            game__tools__pb2.AttachEnergyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/TrackUsage',
            game__tools__pb2.TrackUsageRequest.SerializeToString,
            game__tools__pb2.TrackUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/GetUsageCount',
            game__tools__pb2.GetUsageCountRequest.SerializeToString,
            game__tools__pb2.GetUsageCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendToLostZone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/SendToLostZone',
            game__tools__pb2.SendToLostZoneRequest.SerializeToString,
            game__tools__pb2.SendToLostZoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevealPrize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/RevealPrize',
            game__tools__pb2.RevealPrizeRequest.SerializeToString,
            game__tools__pb2.RevealPrizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyPrizeDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/ModifyPrizeDelta',
            game__tools__pb2.ModifyPrizeDeltaRequest.SerializeToString,
            game__tools__pb2.ModifyPrizeDeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpecialCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_tools.GameToolsService/SetSpecialCondition',
            game__tools__pb2.SetSpecialConditionRequest.SerializeToString,
            game__tools__pb2.SetSpecialConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
